#!/bin/bash

UNIT_NAME=${JUJU_UNIT_NAME//\//_}
CHARM_PATH=$(dirname $0)/..

juju-log "Charm path of '$JUJU_UNIT_NAME'? $CHARM_PATH."

sudo apt-get install --no-install-recommends -y git python-distribute
easy_install pip

juju-log "Deploying hello app."

# Ignore checking for git host
mkdir -p ~/.ssh
if [ ! -e "~/.ssh/config" ]; then
    cat > ~/.ssh/config <<EOF
Host github.com
StrictHostKeyChecking no
UserKnownHostsFile /dev/null
EOF
    cp $CHARM_PATH/keys/id_rsa* ~/.ssh/
    chmod 700 ~/.ssh
    chmod 600 ~/.ssh/*
fi

# Clone app and install dependencies
mkdir -p /srv/$UNIT_NAME
cd /srv/$UNIT_NAME

if [ ! -d ".git" ]; then
    git clone git://github.com/rochacon/juju-playground.git .
else
    git pull
fi
pip install -U -r app/requirements.txt

juju-log "App deployed."

